name: Trigger auto deployment for collaboration-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/backend/CollaborativeNoteEditor.CollaborationService/**'
    - '.github/workflows/collaboration-service-AutoDeployTrigger-7efe131c-0245-4926-a063-af06eeb724e8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: collaborativenoteeditor.azurecr.io
          username: ${{ secrets.COLLABORATIONSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.COLLABORATIONSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: collaborativenoteeditor.azurecr.io/collaboration-service:${{ github.sha }}
          file: src/backend/CollaborativeNoteEditor.CollaborationService/Dockerfile
          context: src/backend/CollaborativeNoteEditor.CollaborationService/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.COLLABORATIONSERVICE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n collaboration-service -g CollaborativeNoteEditor --server collaborativenoteeditor.azurecr.io --username  ${{ secrets.COLLABORATIONSERVICE_REGISTRY_USERNAME }} --password ${{ secrets.COLLABORATIONSERVICE_REGISTRY_PASSWORD }}
            az containerapp update -n collaboration-service -g CollaborativeNoteEditor --image collaborativenoteeditor.azurecr.io/collaboration-service:${{ github.sha }}
