name: Trigger auto deployment for notes-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/backend/NotesService/**'
    - '.github/workflows/notes-service-AutoDeployTrigger-be04261f-c2e0-4b13-8a4c-e9bb3da1d08c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: collaborativenoteeditor.azurecr.io
          username: ${{ secrets.NOTESSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.NOTESSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: collaborativenoteeditor.azurecr.io/notes-service:${{ github.sha }}
          file: src/backend/NotesService/Dockerfile
          context: src/backend/NotesService/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NOTESSERVICE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n notes-service -g CollaborativeNoteEditor --server collaborativenoteeditor.azurecr.io --username  ${{ secrets.NOTESSERVICE_REGISTRY_USERNAME }} --password ${{ secrets.NOTESSERVICE_REGISTRY_PASSWORD }}
            az containerapp update -n notes-service -g CollaborativeNoteEditor --image collaborativenoteeditor.azurecr.io/notes-service:${{ github.sha }}
